spring.application.name=common-model

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/commonDB
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

