# Server Configuration
server.port=8082

# Spring Application Name
spring.application.name=api-gateway

# Spring Cloud Gateway Configuration
spring.cloud.gateway.server.webflux.forwarded.enabled=true

# Route 1 - assignmentoffice
spring.cloud.gateway.server.webflux.routes[0].id=assignmentoffice
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ASSIGNMENTOFFICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/taskassignment/**,/home/**,/task_assignment.css,/assignedTask.css,/viewTask.css,/project.css,/weekly_planner.css,/weekly_report.css,/myProfile.css,/developer.css,/main_dashboard.css,/project_management.css,/images/**,/js/**

# Route 2 - spbootpro
spring.cloud.gateway.server.webflux.routes[1].id=spbootpro
spring.cloud.gateway.server.webflux.routes[1].uri=lb://SPBOOTPRO
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/contra/**,/api/**,/logout,/registereduser,/registeredUser.css

# Route 3 - messageservice
spring.cloud.gateway.server.webflux.routes[2].id=messageservice
spring.cloud.gateway.server.webflux.routes[2].uri=lb://MESSAGESERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/message/**,/chat/**,/sockjs/**

# Route 4 - dashboardservice
spring.cloud.gateway.server.webflux.routes[3].id=dashboardservice
spring.cloud.gateway.server.webflux.routes[3].uri=lb://DASHBOARDSERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/dash/**,/dashboard.css

# Route 5 - email-service
spring.cloud.gateway.server.webflux.routes[4].id=email-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://EMAIL-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/dashboard/**,/css/**

# Eureka Configuration
eureka.instance.prefer-ip-address=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka