server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          forwarded:
            enabled: true
          routes:
            - id: assignmentoffice
              uri: lb://ASSIGNMENTOFFICE
              predicates:
                - Path=/taskassignment/**,/home/**,/task_assignment.css,/assignedTask.css,/viewTask.css,/project.css,/weekly_planner.css,/weekly_report.css,/myProfile.css,/developer.css,/main_dashboard.css,/project_management.css,/images/**,/js/**

            - id: spbootpro
              uri: lb://SPBOOTPRO
              predicates:
                - Path=/contra/**,/api/**,/logout,/registereduser,/registeredUser.css

            - id: messageservice
              uri: lb://MESSAGESERVICE
              predicates:
                - Path=/message/**,/chat/**,/sockjs/**
                
            - id: dashboardservice
              uri: lb://DASHBOARDSERVICE
              predicates:
                - Path=/dash/**,/dashboard.css


            - id: email-service
              uri: lb://EMAIL-SERVICE
              predicates:
               - Path=/email/**,/dashboard/**
eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka