server:
  port: 8087

spring:
  application:
    name: EMAIL-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/EmailServiceDB
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/