api.url=http://localhost:8082
spring.application.name=SPBootPro
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/SpBootProDB
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable multipart
spring.servlet.multipart.enabled=true

# Multipart limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Embedded Tomcat limits (CRITICAL)
server.tomcat.max-swallow-size=10MB
server.tomcat.max-http-form-post-size=10MB

# Eureka Configuration
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shansharma9050@gmail.com
spring.mail.password=kodn sdma mvwb ogff


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
